export default {} = {
    "DZ": ["Algiers", "Oran", "Constantine", "Annaba", "Batna", "Blida", "Sétif", "Chlef", "Djelfa", "Sidi Bel Abbès", "Biskra", "Tébessa", "El Oued", "Skikda", "Tiaret", "Béjaïa", "Tlemcen", "Ouargla", "Béchar", "Mostaganem", "Tizi Ouzou", "Boumerdès", "M'sila", "Mascara", "Guelma", "El Eulma"],
    "BH": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al-Malikiyah", "Adliya", "Sanabis", "Tubli", "Al-Muharraq", "Juffair", "Al-Daih", "Bani Jamrah", "Barbar"],
    "KM": ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo"],
    "DJ": ["Djibouti", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil"],
    "EG": ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El-Mahalla El-Kubra", "Tanta", "Asyut", "Ismailia", "Fayyum", "Zagazig", "Aswan", "Damietta", "Damanhur", "Al-Minya", "Beni Suef", "Hurghada", "Qena", "Sohag", "Shibin El Kom", "Banha", "Kafr El Sheikh", "Arish", "Mallawi", "Bilbeis", "Marsa Matruh", "Idfu"],
    "IQ": ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf", "Sulaymaniyah", "Karbala", "Nasiriyah", "Amara", "Hilla", "Diyala", "Ramadi", "Fallujah", "Tikrit", "Kut", "Dohuk", "Samawah", "Anbar", "Sinjar", "Hit", "Zakho", "Ar Rutbah", "Rawah", "Al-Qaim"],
    "JO": ["Amman", "Zarqa", "Irbid", "Russeifa", "Wadi Al Seer", "Adjloun", "Al-Salt", "Madaba", "Ar Ramtha", "Al Mafraq", "Ma'an", "Al-Karak", "Jarash", "Tafila", "Aqaba"],
    "KW": ["Kuwait City", "Ahmadi", "Hawalli", "Salmiya", "Jahra", "Fahaheel", "Al Farwaniyah", "Al Fahahil", "Ar Rabiyah", "Sabah as Salim", "Salwa"],
    "LB": ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos", "Jounieh", "Zahle", "Baalbek", "Batroun", "Chouf District", "Aley", "Keserwan District", "Marjayoun", "Bint Jbeil", "Hasbaya", "Hermel"],
    "LY": ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Zawiya", "Zliten", "Al Khums", "Sabha", "Sirte", "Derna", "Zintan", "Yafran", "Ghat", "Murzuk", "Ubari", "Nalut", "Waddan", "Bani Walid", "Jadu", "Awjilah", "Jalu", "Jaghbub", "Ras Lanuf", "Al Bayda", "Ghadames"],
    "MR": ["Nouakchott", "Nouadhibou", "Zouérat", "Rosso", "Adel Bagrou", "Aleg", "Kiffa", "Akjoujt", "Atar", "Néma", "Kaédi", "Bogue", "Tidjikja", "Boutilimit", "Aïoun El Atrouss", "Voinjama", "Araouane", "Bir Moghrein"],
    "MA": ["Casablanca", "Fez", "Rabat", "Marrakech", "Agadir", "Tangier", "Oujda", "Kenitra", "Tetouan", "Safi", "Mohammedia", "Khouribga", "Beni Mellal", "El Jadida", "Taza", "Nador", "Settat", "Berrechid", "Khémisset", "Inezgane", "Larache", "Ksar El Kebir", "Guelmim", "Essaouira", "Chefchaouen"],
    "OM": ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar", "As Sib", "Al Buraimi", "Nizwa", "Sur", "Rustaq", "Samail", "Ibri", "Izki", "Bahla", "Barka", "Adam", "Yanqul", "Ibra", "Ibri", "Khasab"],
    "PS": ["Gaza City", "Khan Yunis", "Hebron", "Nablus", "Rafah", "Jabalia", "Jenin", "Tulkarm", "Bethlehem", "Al Bireh", "Qalqilya"],
    "QA": ["Doha", "Al Wakrah", "Al Khor", "Umm Salal Mohammed", "Al Rayyan", "Mesaieed", "Al Shamal", "Al Daayen"],
    "SA": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Tabuk", "Al-Khobar", "Ta'if", "Buraidah", "Khobar", "Abha", "Jizan", "Yanbu", "Najran", "Hail", "Qatif", "Khamis Mushait", "Hofuf", "Hafar Al-Batin", "Ras Tanura", "Al Jubail", "Dhahran", "Ha'il", "Al-Qunfudhah", "Al-Qurayyat", "Al Bahah", "Arar", "Sakakah", "Al Majma'ah", "Rafha", "Tarut Island"],
    "SO": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Garoowe", "Jowhar", "Beledweyne", "Baidoa", "Berbera", "Galkayo", "Afmadow", "Burao", "Baardheere", "Buulobarde", "Marka", "Jilib", "Afmadow", "Hobyo", "Eyl", "Ceelbuur", "Wanlaweyn", "Qardho", "Dusa Marreb", "Luuq", "Xudur"],
    "SD": ["Khartoum", "Omdurman", "Nyala", "Port Sudan", "Kassala", "Al-Ubayyid", "Kosti", "Wad Madani", "El Fasher", "El Geneina", "Atbara", "Rabak", "Ed Dueim", "Ad-Damazin", "El-Obeid", "Singa", "El Daein", "Dongola", "Al-Qadarif", "Kaduqli", "Bara", "En Nahud", "Al-Fashir", "Marawi", "Zalingei", "Um Ruwaba"],
    "SY": ["Damascus", "Aleppo", "Homs", "Hama", "Latakia", "Raqqa", "Deir ez-Zor", "Al-Hasakah", "Qamishli", "Daraa", "Idlib", "As-Suwayda", "Tartus"],
    "TN": ["Tunis", "Sfax", "Sousse", "Ettadhamen", "Kairouan", "Bizerte", "Gabès", "Aryanah", "Gafsa", "El Mourouj", "Kasserine", "Zarzis", "La Goulette", "Douz", "Houmt El Souk", "Korba", "Monastir", "Médenine", "Mahdia", "Menzel Bourguiba", "Skhira", "Jendouba", "Beni Khiar", "Mateur", "Ain Draham"],
    "AE": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Dibba Al-Fujairah", "Dibba Al-Hisn", "Kalba", "Jebel Ali", "Hatta", "Liwa Oasis"],
    "YE": ["Sana'a", "Aden", "Taiz", "Hodeidah", "Ad Dali'", "Ibb", "Al Mukalla", "Zinjibar", "Say'un", "Sadar", "Al Hudaydah", "Marib", "Dhamar", "Yarim", "Ash Shihr", "Lahij", "Al Ghaydah", "Sa'dah", "Zabid", "Al Bayda'", "Al Hazm", "Ataq"]
};

export let cityNames = [
    "Algeria",
    "Manama",
    "Moroni",
    "Djibouti City",
    "Egypt",
    "Baghdad",
    "Amman",
    "Kuwait City",
    "Beirut",
    "Tripoli",
    "Nouakchott",
    "Rabat",
    "Muscat",
    "Ramallah",
    "Doha",
    "Riyadh",
    "Mogadishu",
    "Khartoum",
    "Damascus",
    "Tunis",
    "Abu Dhabi",
    "Sana'a",
];