export default {} = {
    "AE": ["Abu Dhabi", "Ajman", "Al Ain", "Dibba Al-Fujairah", "Dibba Al-Hisn", "Dubai", "Fujairah", "Hatta", "Jebel Ali", "Kalba", "Khor Fakkan", "Liwa Oasis", "Ras Al Khaimah", "Sharjah", "Umm Al Quwain"],
    "BH": ["A'ali", "Adliya", "Al-Daih", "Al-Malikiyah", "Al-Muharraq", "Bani Jamrah", "Barbar", "Budaiya", "Hamad Town", "Isa Town", "Jidhafs", "Juffair", "Manama", "Muharraq", "Riffa", "Sanabis", "Sitra", "Tubli"],
    "DJ": ["Ali Sabieh", "Dikhil", "Djibouti", "Obock", "Tadjourah"],
    "EG": ["Al-Minya", "Alexandria", "Arish", "Aswan", "Asyut", "Banha", "Beni Suef", "Bilbeis", "Cairo", "Damanhur", "Damietta", "Fayyum", "Giza", "Hurghada", "Idfu", "Ismailia", "Kafr El Sheikh", "Mallawi", "Mansoura", "Marsa Matruh", "Port Said", "Qena", "Shibin El Kom", "Shubra El-Kheima", "Sohag", "Suez", "Tanta", "Zagazig"],
    "IQ": ["Al-Qaim", "Amara", "Anbar", "Ar Rutbah", "Baghdad", "Diyala", "Dohuk", "Erbil", "Fallujah", "Hit", "Karbala", "Kirkuk", "Kut", "Mosul", "Najaf", "Ramadi", "Rawah", "Samawah", "Sinjar", "Sulaymaniyah", "Tikrit", "Zakho"],
    "JO": ["Adjloun", "Aqaba", "Ar Ramtha", "Irbid", "Jarash", "Ma'an", "Madaba", "Tafila", "Zarqa", "Al Mafraq", "Al-Karak", "Al-Salt", "Wadi Al Seer"],
    "KM": ["Domoni", "Fomboni", "Moroni", "Mutsamudu", "Tsimbeo"],
    "KW": ["Ahmadi", "Al Fahahil", "Al Farwaniyah", "Ar Rabiyah", "Fahaheel", "Hawalli", "Jahra", "Kuwait City", "Salwa", "Salmiya", "Sabah as Salim"],
    "LB": ["Aley", "Baalbek", "Batroun", "Beirut", "Bint Jbeil", "Byblos", "Chouf District", "Hasbaya", "Hermel", "Jounieh", "Keserwan District", "Marjayoun", "Sidon", "Tripoli", "Tyre", "Zahle"],
    "LY": ["Al Bayda", "Al Khums", "Al-Khums", "Awjilah", "Bani Walid", "Benghazi", "Derna", "Ghat", "Ghadames", "Jadu", "Jaghbub", "Misrata", "Murzuk", "Nalut", "Ras Lanuf", "Sabha", "Sirte", "Tarhuna", "Ubari", "Waddan", "Yafran", "Zawiya", "Zintan"],
    "MA": ["Agadir", "Beni Mellal", "Berrechid", "Casablanca", "Chefchaouen", "El Jadida", "Essaouira", "Fez", "Guelmim", "Kenitra", "Khouribga", "La Goulette", "Larache", "Marrakech", "Meknes", "Mohammedia", "Oujda", "Rabat", "Safi", "Settat", "Tangier", "Taza", "Tetouan"],
    "MR": ["Aïoun El Atrouss", "Adel Bagrou", "Akjoujt", "Aleg", "Araouane", "Atar", "Bir Moghrein", "Bogue", "Boutilimit", "Kaédi", "Néma", "Nouadhibou", "Nouakchott", "Rosso", "Tidjikja", "Voinjama", "Zouérat"],
    "OM": ["Adam", "Al Buraimi", "Al Khaburah", "Al Rustaq", "Al-Buraimi", "Al-Fujairah", "As Sib", "Bahla", "Barka", "Bawshar", "Dibba Al-Baya", "Ibri", "Izki", "Khasab", "Muscat", "Nizwa", "Salalah", "Samail", "Seeb", "Sohar", "Sur", "Yanqul"],
    "PS": ["Al Bireh", "Bethlehem", "Gaza City", "Hebron", "Jabalia", "Jenin", "Khan Yunis", "Nablus", "Qalqilya", "Rafah", "Tulkarm"],
    "QA": ["Al Daayen", "Al Khor", "Al Rayyan", "Al Shamal", "Doha", "Mesaieed", "Umm Salal Mohammed", "Al Wakrah"],
    "SA": ["Abha", "Al Bahah", "Al Jubail", "Al Khobar", "Al-Qunfudhah", "Arar", "Buraidah", "Dammam", "Dhahran", "Hafar Al-Batin", "Hail", "Jeddah", "Jizan", "Khamis Mushait", "Khobar", "Madinah", "Makkah", "Najran", "Ras Tanura", "Riyadh", "Sakakah", "Tabuk", "Ta'if", "Tarut Island", "Yanbu"],
    "SD": ["Ad-Damazin", "Al-Ubayyid", "Atbara", "Bara", "Dongola", "Ed Dueim", "El Daein", "El Fasher", "El Geneina", "En Nahud", "Kaduqli", "Kassala", "Khartoum", "Kosti", "Marawi", "Nyala", "Port Sudan", "Rabak", "Singa", "Um Ruwaba", "Wad Madani", "Zalingei"],
    "SO": ["Afmadow", "Baardheere", "Baidoa", "Beledweyne", "Berbera", "Bosaso", "Buulobarde", "Burao", "Ceelbuur", "Dusa Marreb", "Eyl", "Galkayo", "Garoowe", "Hargeisa", "Hobyo", "Jilib", "Jowhar", "Kismayo", "Luuq", "Marka", "Mogadishu", "Qardho", "Wanlaweyn", "Xudur"],
    "SY": ["Aleppo", "Al-Hasakah", "As-Suwayda", "Daraa", "Deir ez-Zor", "Hama", "Homs", "Idlib", "Latakia", "Qamishli", "Raqqa", "Tartus", "Damascus"],
    "TN": ["Ain Draham", "Aryanah", "Beni Khiar", "Bizerte", "Douz", "El Mourouj", "Ettadhamen", "Gabès", "Gafsa", "Houmt El Souk", "Jendouba", "Kairouan", "Kasserine", "Korba", "La Goulette", "Mahdia", "Mateur", "Médenine", "Menzel Bourguiba", "Monastir", "Nabeul", "Sfax", "Skhira", "Sousse", "Tataouine", "Tunis", "Zarzis"],
    "YE": ["Ad Dali'", "Aden", "Al Bayda'", "Al Ghaydah", "Al Hudaydah", "Al Mukalla", "Al Shihr", "Ataq", "Dhamar", "Hodeidah", "Ibb", "Lahij", "Marib", "Sa'dah", "Sadar", "Sana'a", "Say'un", "Taiz", "Yarim", "Zabid", "Zinjibar"]
}

export let cityNames = {
    "AE": "United Arab Emirates",
    "BH": "Bahrain",
    "DJ": "Djibouti",
    "EG": "Egypt",
    "IQ": "Iraq",
    "JO": "Jordan",
    "KM": "Comoros",
    "KW": "Kuwait",
    "LB": "Lebanon",
    "LY": "Libya",
    "MR": "Mauritania",
    "MA": "Morocco",
    "OM": "Oman",
    "PS": "Palestine",
    "QA": "Qatar",
    "SA": "Saudi Arabia",
    "SO": "Somalia",
    "SD": "Sudan",
    "SY": "Syria",
    "TN": "Tunisia",
    "YE": "Yemen"
};
